name: workflow-ci

on: 
  push: 
    branches:
      - develop

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: node-version
        run: node -v

      - name: npm-version
        run: npm -v

